firstname=input('Enter first name:')
lastname=input('Enter last name:')
address=input('Enter Address:')
city=input('Enter city:')
state=input('Enter state code:')
post=input('enter zip code:')
wname=firstname+''+lastname
print('\n')
print(wname)
print(address)
print(city,', ',state,'  ', post)
